// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migadddateslider : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migadddateslider));
        
        string IMigrationMetadata.Id
        {
            get { return "202109221629370_mig-add-date-slider"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
