// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migupdatepublicc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migupdatepublicc));
        
        string IMigrationMetadata.Id
        {
            get { return "202109061338334_mig-update-publicc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
