// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaddcommentmember : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaddcommentmember));
        
        string IMigrationMetadata.Id
        {
            get { return "202108240749260_mig-add-commentmember"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
